### PR TITLE
Replace HashMap<String, String> with HeaderMap for storing headers

### PR DESCRIPTION
**Pull request by glebpom**

### CODE REVIEW

**Comment by durch** [comment]
Looks great, will publish new version today, thank you!

**Comment by glebpom** [comment]
not sure about tests - some of them are still falling

**Comment by durch** [comment]
Those are fine, they depend on the secrets in the repo, so they only work if PRs originate from the repo. Its a hassle for people committing, but I've not found a workaround yet :(

**Comment by durch** [comment]
`0.27.0-beta6` published

**Pull request merged**
