### PR TITLE
Re-introduce proper error handling with thiserror

### PR DESCRIPTION
**Pull request by nightmared**
This is a repost of #166 (rebased on top of master), because I don't know why you closed the previous PR, and thus if this feature is wanted or not ?

Following discussion at #164, this PR replaces anyhow with thiserror to make errors more explicit, comparable, and so on. The goal is for consumers of this library to be able to extract information about errors without having to downcast anyhow errors, and thus to have more granularity to filter the errors and/or understand the issue at hand.

As an important note, this is not API compatible with the current 0.27 branch and probably harder to accept that when rust-s3 0.27 was still in beta.

### CODE REVIEW

**Comment by nightmared** [comment]
Sure, let me rebase this ;)

**Comment by nightmared** [comment]
Also:
Since https://github.com/durch/rust-s3/commit/c00a18693e53da096dd6e59d6e7880f2add6039f, 
the function is_ec2 (https://github.com/durch/rust-s3/blob/c00a18693e53da096dd6e59d6e7880f2add6039f/aws-creds/src/credentials.rs#L315) is no longer useful. So I will prune it in the rebase. Is that ok?

**Comment by nightmared** [comment]
The CI failures look more like, well, a *CI failure* than something else :p
```
failures:
    bucket::test::aws_put_head_get_delete_object
    bucket::test::digital_ocean_test_put_head_get_delete_object
    bucket::test::gc_test_put_head_get_delete_object
    bucket::test::minio_test_put_head_get_delete_object
    bucket::test::streaming_test_put_get_delete_big_object
    bucket::test::test_bucket_create_delete_default_region
    bucket::test::test_bucket_create_delete_non_default_region
    bucket::test::test_bucket_create_delete_non_default_region_public
    bucket::test::test_tagging_aws
    bucket::test::wasabi_test_put_head_get_delete_object
```

**Comment by durch** [comment]
@nightmared crate definitely needs to go to `thiserror`, I'll work on it in the next couple of months for sure.

**Comment by durch** [comment]
@nightmared I think these get closed when I cleanup old branches, I'd be very happy to take another look, the anyhow hack was always meant to be temporary, but these always end up being permanent :)

**Comment by durch** [comment]
Released in 0.31, any improvements are welcome

**Pull request closed without merging**
