### PR TITLE
Allow types other than string slices for local paths

### PR DESCRIPTION
**Pull request by jplatte**
Before this, local paths obtained through directory traversal, `tempfile::NamedFile::path` or anything like that would first have to be converted to strings, which does UTF8 validation and is just generally pointless boilerplate.

This is a breaking change since it can break type inference (for example if people were calling `.put_object_stream(my_local_path.as_ref(), my_s3_path)`).

### CODE REVIEW

**Comment by jplatte** [comment]
Once std has `AsyncRead` it would probably make sense to also have a variant of `put_object_stream` that takes any `AsyncRead`. You could do this now with `async-std`s `AsyncRead`, I guess it's not much different from this PR which also exposes an `async-std` type in the public API (though I can change it to `std::path::Path` if you want, which is convertible to `async_std::path::Path`, if you prefer).

**Comment by jplatte** [comment]
Rebased. Ping @durch

**Comment by durch** [comment]
@jgoday I have no strong opinions here, as long as we keep making the API more ergonomic. Having a `pub_object_stream` generic over `AsyncRead` would be nice for sure :)

**Comment by jplatte** [comment]
Awesome. By the way, how about setting up a dev chat? (I personally prefer Matrix, Zulip would be cool too)

**Comment by durch** [comment]
@jplatte published to crates.io as `0.26.0`

**Pull request merged**
