### PR TITLE
Migrate to hyper v1 and http v1

### PR DESCRIPTION
**Pull request by negezor**
Hi, this PR updates hyper to v1 and http to v1. I'm not completely sure about the choices I made, so some things might have been overcomplicated. But it is somewhat hard to understand the new hyper.

I would be happy to be pointed out possible improvements. But for now it gives me the opportunity not to duplicate hyper `0.2` and `1.1` already now.

It also updates side dependencies that it's time to update. It's also worth thinking about updating edition to 2021.

### CODE REVIEW

**Comment by negezor** [comment]
@durch gentle ping

**Comment by durch** [comment]
@negezor thanks for this, I need access to my main laptop to test, will get it sorted within a week.

**Comment by durch** [comment]
@negezor seeing a bunch of hangups in tests, not sure what thats about, will need to take a closer look at what is happening internally

**Comment by qdrs** [comment]
@durch Any update on this?

**Comment by rakshith-ravi** [comment]
@durch is there anything we can do to help?

**Comment by vnghia** [comment]
Hi @negezor, I've just reached out @durch by email and this is what he said
> appreciate the bump and support around development, its a pretty big PR, it slipped again, I'll give it some attention, and do my best to merge it this week.

> Always appreciate community help, a branch that rebases it on top of current master would be great 🙂

Could you rebase it to master ? Thank you!

**Comment by rakshith-ravi** [comment]
Hi @negezor. Happy to help with the rebase if you'd like. Please don't hesitate to reach out for help.

For everybody who is subscribed to this issue - 0.35 is still in alpha and I was thinking of getting this in for the 0.35 release. Hope we can all collaborate towards the same goal

**Comment by rakshith-ravi** [comment]
Also, thanks for the update @vnghia!

**Comment by vnghia** [comment]
I have some freetime this week so I will do a rebase myself if @negezor doesn't have time this week

**Comment by rakshith-ravi** [comment]
Out of curiosity, is there a way to do the rebase and put it as a part of the same PR? I assume if anybody else were to do the rebase it will be a separate PR, yeah? (Mostly just concerned about @negezor not getting recognized for the contribution)

**Comment by vnghia** [comment]
All the commits made by @negezor will still be credited for them so I don't think it is a big issue

**Comment by vnghia** [comment]
I am putting a really draft PR #400 here but to be honest I am not really sure this is the right thing because it seems that `hyper` now drop the `client` and we have to activate a `client-legacy` feature to get it. I don't think depends on something `legacy` is a good idea and `hyper` suggests that we should switch to `reqwest` since `hyper` should only be used for something really low-level. I am waiting for @durch opinion on this

**Comment by durch** [comment]
> I am putting a really draft PR #400 here but to be honest I am not really sure this is the right thing because it seems that `hyper` now drop the `client` and we have to activate a `client-legacy` feature to get it. I don't think depends on something `legacy` is a good idea and `hyper` suggests that we should switch to `reqwest` since `hyper` should only be used for something really low-level. I am waiting for @durch opinion on this.

I originally moved away from `reqwest` as its quite heavy for what the library is using it, that being said maybe its worth revisiting with a really slimmed down set of features... Not sure, I'd like to optimize for usability and maintainability. @vnghia how much of a chore would it be to migrate to `reqwest`, does it feel like a days or a weeks of work thing?

**Comment by vnghia** [comment]
I can't really tell how much work is needed to migrate to `reqwest` but I can send a PR for you to review. I list a non-exhausively pros/cons of `reqwest` here:

Pros:
	- Abstract away `native-tls` and `rustls`, which is really good since we have a couple of issues related to this.
	- Abstract away `hyper` and we don't have to depend on `hyper_util::client::legacy`.

Cons:
	- We will have to use `tokio` runtime.
	- Heavy as you said.

If you think it is worth experiment, I can try to work on migrating to `reqwest`.

**Comment by durch** [comment]
> I can't really tell how much work is needed to migrate to `reqwest` but I can send a PR for you to review. I list a non-exhausively pros/cons of `reqwest` here:
> 
> Pros: - Abstract away `native-tls` and `rustls`, which is really good since we have a couple of issues related to this. - Abstract away `hyper` and we don't have to depend on `hyper_util::client::legacy`.
> 
> Cons: - We will have to use `tokio` runtime. - Heavy as you said.
> 
> If you think it is worth experiment, I can try to work on migrating to `reqwest`.
> 
> Edit: if you want to work with `http2`, `reqwest` might be the only choice (expect implement everything in `hyper` manually`) since here: [algesten/ureq#540](https://github.com/algesten/ureq/issues/540)

I think its worth it, I might have an easier time doing it, since I did it once already, I moved away from `reqwests` and onto `hyper`. Working with `reqwest` is in many ways nicer then with hyper. My head is currently in this, so I'll likely give it a go over the weekend, that being said, feel free to beat me too it, I might get sidetracked :)

**Comment by durch** [comment]
Decided to move to request, it makes for a more maintainable and readable codebase, available in `0.36.0-alpha.2`

**Pull request closed without merging**
