### PR TITLE
Lumeohq presign fix

### PR DESCRIPTION
**Pull request by durch**
Continuation of #225

### CODE REVIEW

**Comment by durch** [comment]
@jplatte looks like this blows up `presign` tests, as the slashes in paths do not get encoded, holding off on merging for now

**Comment by jplatte** [comment]
You have some string comparisons in those tests where you explicitly test whether `%2F` or `/` is encoded. It's obvious that they would change, but have you tested whether this works with actual S3 server implementations?

**Comment by durch** [comment]
> You have some string comparisons in those tests where you explicitly test whether `%2F` or `/` is encoded. It's obvious that they would no longer pass, but have you tested whether this works with actual S3 server implementations?

No, good point, lets see whats what in reality :)

**Comment by jplatte** [comment]
@durch Any update on this?

**Comment by durch** [comment]
@jplatte just looking into this again, thanks for the patience

**Comment by jplatte** [comment]
Looks like this wasn't included in v0.28.0 or v0.28.1, was that intentional?

**Comment by jplatte** [comment]
@durch Was this removed again intentionally? Looks like the commit you merged into develop never made it to master, and now you removed it from develop too 🙁

**Pull request merged**
