### PR TITLE
Add HeadObject command

### PR DESCRIPTION
**Pull request by jdon**
Added the HeadObject command.

I have updated the tests to include this command.
I only have access to AWS so I was only able to actually run the aws tests:
* `test_put_head_get_delete_object` 
* `test_put_head_get_delete_object_blocking`

I'm assuming that they will pass for GC and wasabi.

Please let me know if I can make any improvements or if there is a better way to make the changes etc.

### CODE REVIEW

**Comment by jdon** [comment]
@durch 
Should the `test --ignored` step pass?
As it looks like some of the unchanged tests also failed.

**Comment by durch** [comment]
@jdon Thank you for the PR, I'll review it promptly. Unfortunately `--ignored` tests won't pass on a fork PR as they rely on a bunch of secrets in the main repo, no worries there

**Review by durch — APPROVED** [review]

**Comment by durch** [comment]
@jdon published in `0.26.3`

**Comment by jdon** [comment]
@durch thanks for reviewing and merging this.

**Pull request merged**
