### PR TITLE
0.19.0 - futures 0.3, async/.await

### PR DESCRIPTION
**Pull request by durch**
Will be merged to master only after all crates we're depending on have been graduated out of at least alpha status.

---
This change is [Reviewable](https://reviewable.io/reviews/durch/rust-s3/61)

### CODE REVIEW

**Comment by durch** [comment]
Tests are broken due to virtual path style, will get fixed

**Comment by psmit** [comment]
Both reqwest and tokio have now released new non-alpha versions.

**Comment by durch** [comment]
@psmit thank you for the heads up. Barring any issues this will be merged in the next week or two, thank you for your patience!

**Comment by durch** [comment]
Closing, `0.19.0-2` merged to master

**Pull request closed without merging**
